[2024-04-02T21:15:52.515+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: food_pipeline_dag_v01.download_data manual__2024-04-02T21:15:50.170204+00:00 [queued]>
[2024-04-02T21:15:52.534+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: food_pipeline_dag_v01.download_data manual__2024-04-02T21:15:50.170204+00:00 [queued]>
[2024-04-02T21:15:52.535+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-04-02T21:15:52.558+0000] {taskinstance.py:2217} INFO - Executing <Task(BashOperator): download_data> on 2024-04-02 21:15:50.170204+00:00
[2024-04-02T21:15:52.572+0000] {standard_task_runner.py:60} INFO - Started process 425 to run task
[2024-04-02T21:15:52.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'food_pipeline_dag_v01', 'download_data', 'manual__2024-04-02T21:15:50.170204+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/food_dag.py', '--cfg-path', '/tmp/tmpy52o1oa6']
[2024-04-02T21:15:52.580+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask download_data
[2024-04-02T21:15:52.659+0000] {task_command.py:423} INFO - Running <TaskInstance: food_pipeline_dag_v01.download_data manual__2024-04-02T21:15:50.170204+00:00 [running]> on host b708511acde3
[2024-04-02T21:15:52.783+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kenneth' AIRFLOW_CTX_DAG_ID='food_pipeline_dag_v01' AIRFLOW_CTX_TASK_ID='download_data' AIRFLOW_CTX_EXECUTION_DATE='2024-04-02T21:15:50.170204+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-02T21:15:50.170204+00:00'
[2024-04-02T21:15:52.785+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-04-02T21:15:52.788+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'wget https://fsa-catalogue2.s3.eu-west-2.amazonaws.com/Approved+establishments+01-03-2024.csv -O data.csv']
[2024-04-02T21:15:52.809+0000] {subprocess.py:86} INFO - Output:
[2024-04-02T21:15:52.816+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: wget: command not found
[2024-04-02T21:15:52.817+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-04-02T21:15:52.837+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-04-02T21:15:52.845+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=food_pipeline_dag_v01, task_id=download_data, execution_date=20240402T211550, start_date=20240402T211552, end_date=20240402T211552
[2024-04-02T21:15:52.875+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 7 for task download_data (Bash command failed. The command returned a non-zero exit code 127.; 425)
[2024-04-02T21:15:52.914+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-04-02T21:15:52.953+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
